---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present
    - name: Set up Docker's apt keyrings directory
      command: mkdir -m 0755 -p /etc/apt/keyrings
    - name: Download Docker's official GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o
        /etc/apt/keyrings/docker.asc
    - name: Set appropriate permissions for Docker GPG key file
      command: chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add Docker repository to Apt sources
      command: >
        echo "deb [arch=$(dpkg --print-architecture)
        signed-by=/etc/apt/keyrings/docker.asc]
        https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo
        "$VERSION_CODENAME") stable" | sudo tee
        /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Update apt cache after adding repository
      apt:
        update_cache: yes
    - name: Install Docker packages
      apt:
        name:
          - docker.io
        state: present
    - name: Run Hello-world
      command: docker run hello-world
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Copy file from local to remote
      ansible.builtin.copy:
        src: /home/sehnsucht/Github/College/Applied_DevOps/iac/ansible/run-container.sh
        dest: /home/ubuntu/run-container.sh
        remote_src: no
    - name: Remove carriage return characters from the script file
      ansible.builtin.shell: sed -i 's/\r$//' /home/ubuntu/run-container.sh
    - name: Grant execute permission to the script
      ansible.builtin.command: chmod +x /home/ubuntu/run-container.sh
    - name: Debug remote host file system
      ansible.builtin.shell: ls -l /home/ubuntu/run-container.sh
      register: debug_output
    - name: Print debug output
      debug:
        var: debug_output.stdout_lines
    - name: Giving permission to docker socket
      ansible.builtin.shell: sudo chmod 666 /var/run/docker.sock
    - name: Run the script on the remote host
      ansible.builtin.shell: /home/ubuntu/run-container.sh
      register: script_output
    - name: Print script output
      debug:
        var: script_output.stdout_lines
