name: Node.js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    name: Build Next.js app

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/to-do-list

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: List directory contents
      run: ls -al

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t vaibhavrawat/to-do-list-frontend:latest .
        docker tag vaibhavrawat/to-do-list-frontend:latest vaibhavrawat/to-do-list-frontend:latest

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: Frontend/to-do-list
        push: true
        tags: |
          vaibhavrawat/to-do-list-frontend:latest
          vaibhavrawat/to-do-list-frontend:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
