name: Node.js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Navigate to project directory
      run: cd Frontend/to-do-list

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t deepanshurawat6/to-do-list-frontend:latest .
        docker tag deepanshurawat6/to-do-list-frontend:latest deepanshurawat6/to-do-list-frontend:latest

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: Frontend/to-do-list
        push: true
        tags: |
          deepanshurawat6/to-do-list-frontend:latest
          deepanshurawat6/to-do-list-frontend:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
